### PR TITLE
Update core_ro-ro.json

### PR DESCRIPTION
**Pull request by CosminPerRam**
Translating to Romanian the "Support && FAQ" line.
Changing the word "Fă" to "Apasă" from "core_balloon_info" line.
Changing the word "Fă" to "Crează" from "core_tray_take_screenshot" line.
Correcting an grammatical error, "Aplicașie" to "Aplicație" from "core_msgboxtitle_app_conflict" line.
Changing the word "Ele" to "Acestea" from "core_updater_status_compat_message_box_body" line.

### CODE REVIEW

**Comment by andi257** [comment]
Scuze, greșeala mea, dar vezi că se scrie „creează”, nu „crează”.

**Comment by CosminPerRam** [comment]
Aw, da, oricum, am sa creez altul mai incolo ca am mai vazut niste greseli dar multumesc mult de observatie.

**Comment by Biohazard90** [comment]
Hey, could someone check out the conflicts in ui_ro-ro? If I use Google translate it will probably not suffice for a good result.

**Comment by CosminPerRam** [comment]
Done

**Pull request merged**
