### PR TITLE
Pull request - new translation: slovenian (slovenščina)

### PR DESCRIPTION
**Pull request by AndrazSpan**
Hello!

I'm sending files for slovenian translation.
I hope they are ok because i could not test them, because they did not show up in language selection box after copying files to correct folder.

files are located here (I had some problems with uploading it to github): https://1drv.ms/f/s!ApUTHry3VihUiUsz4s4J4B2G6Ve8

Best regards, Andraz Span.

### CODE REVIEW

**Comment by Biohazard90** [comment]
Hey, thanks!
It looks like there are some problems though, do you think you could try the files out by changing their name to a language that has been registered already and then select that language to test them?

You can basically use any other language for testing purposes, except for en-us, because that is always loaded as a fallback.

**Comment by AndrazSpan** [comment]
Hi!

Thanks for the warning about errors and for letting me know how to test the translation.

I had repaired the error and also corrected some to long translations.
The new files are loaded to same place as before, you may use the same url.

Best regards, Andraz Span.

**Comment by AndrazSpan** [comment]
Hi!

Are the new files ok?

Best regards, Andraz Span.

**Comment by Biohazard90** [comment]
Hey, sorry, I haven't been able to update translations since a few weeks, I tried to focus on programming to get the next changes done. The patch after this next one will be purely dedicated to updating translations and bug fixes.

**Comment by Biohazard90** [comment]
I checked out the files now and added the language for the next patch, thanks! I'll close this pull request.

**Pull request closed without merging**
